[package]
name = "asteroids"
version = "0.1.0"
authors = ["olya <olya@ivanovs.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.26.0"
gl = "0.14.0"
nalgebra-glm = "0.7.0"  
stb_image = "0.2.3" 